export const FETCH_MAIN_COURSES='FETCH_MAIN_COURSES';
export const FETCH_APPETIZERS='FETCH_APPETIZERS';
export const FETCH_DESSERTS='FETCH_DESSERTS';
export const FETCH_DRINKS='FETCH_DRINKS';
export const FETCH_DISH='FETCH_DISH';
export const FETCH_DRINK='FETCH_DRINK';
export const FETCH_INGREDIENTS='FETCH_INGREDIENTS';